function spmup_review_despike_log(varargin)

% SPM U+ utility to review the log file generated by 
% spmup_despike - it will generate a figure that show
% which voxels were despiked ; the figure is pause at
% each volume, simply stroke a key to move forward

if nargin == 0
    [f,p]=uigetfile('spmup_despike_log.mat','Select a despike log');
    cd(p); load(f)
else
    load(varargin{1});    
end

if isempty(spmup_despike_log.despiked_voxels)
    figure('Name','Proportion of outlying voxels')
    plot(spmup_despike_log.outlying_voxels,'LineWidth',3); grid on;
    xlabel('volumes','Fontsize',12); axis tight
    ylabel('percentage of outlying voxels','Fontsize',12);
    title('Volume Outlier detection - No despiking performed','Fontsize',14); hold on
    plot(spmup_despike_log.outlying_volumes.*(max(spmup_despike_log.outlying_voxels)-mean(spmup_despike_log.outlying_voxels))+mean(spmup_despike_log.outlying_voxels),'or','LineWidth',2);
else
    figure('Name','Despiking')
    subplot(2,2,[1 2]);
    plot(spmup_despike_log.outlying_voxels,'LineWidth',3); grid on;
    xlabel('volumes','Fontsize',12); axis tight
    ylabel('percentage of outlying voxels','Fontsize',12);
    title('Volume Outlier detection','Fontsize',14); hold on
    plot(spmup_despike_log.outlying_volumes.*(max(spmup_despike_log.outlying_voxels)-mean(spmup_despike_log.outlying_voxels))+mean(spmup_despike_log.outlying_voxels),'or','LineWidth',2);
    subplot(2,2,[3 4]);
    plot(spmup_despike_log.despiked_voxels,'LineWidth',3); grid on;
    xlabel('volumes','Fontsize',12); axis tight
    ylabel('percentage of despiked voxels ','Fontsize',12);
    title('Voxel despiked','Fontsize',14); hold on
    tmp = single(spmup_despike_log.outlying_volumes);
    tmp(find(tmp==0)) = NaN;
    plot(tmp.*mean(spmup_despike_log.despiked_voxels),'or','LineWidth',2);
end

if ~isempty(spmup_despike_log.despiked_voxels)
    
    if isfield(spmup_despike_log.P)
        V = spm_vol(spmup_despike_log.P);
        Y = spm_read_vols(V);
        Avg = mean(Y,4);
    else
        [M,sts] = spm_select(1,'image','select reference image to plot data on',[],pwd,'.*',1);
        if sts ~=0
            Avg = spm_read_vols(spm_vol(M));
        else
            error('spm u+ stopped - file selection interupted')
        end
    end
    
    figure('Name','Despiked Voxels')
    colormap('jet')
    for z=1:size(Avg,3);
        subplot(2,2,1); imagesc(flipud(Avg(:,:,z)'));
        axis square; title(['Slice ' num2str(z)],'FontSize',14)
        subplot(2,2,2);
        tmp = squeeze(spmup_despike_log.class(:,:,z,:));
        imagesc(flipud(nansum(tmp,3)')); axis square
        title('Voxels despiked','FontSize',14)
        subplot(2,2,[3 4]);
        new = reshape(shiftdim(tmp,2),size(tmp,3),size(tmp,1)*size(tmp,2));
        imagesc(new'); xlabel('Volumes','FontSize',12);
        ylabel('position x*y','FontSize',12); 
        title('data points despiked','FontSize',14); 
        pause
    end
end


