function options = spmup_getoptions(BIDS_dir)

% routine to return all the spmup options with defaults set
%
% FORMAT options = spmup_getoptions(BIDS_dir)
% INPUT BIDS_dir is a folder in which analyses should be carried on
% OUTPUT options is a structure with spmup optional default parameters set
%               'outdir' where to write the data (default is [BIDS_dir filesep 'derivatives'])
%               'keep_data' is 'off' (default) or 'on' to keep all steps 
%                           off means only the last processed data are available
%               'overwrite_data' 'on' (default) turning it 'off' is useful to restart
%               	             some processing while kepping previous steps
%               'QC' 'on' (default) or 'off' performs quality control (also augment motion regressor file) 
%               'anat' a cell array of file pattern to use e.g. {'acq_MPRAGE_T1w','acq_SPACE_T2w'} 
%               'reorient' is 'on' (default) to automatically set (0,0,0)
%               'removeNvol' set to '0' (default) is the number of initial volumes to remove
%               'task' [] (default) to specificy which bold task to analyze.
%               'acq'  [] (default) to specificy which bold acquisition to analyze.
%               'rec'  [] (default) to specificy which bold reconstruction to analyze.
%               'despike' can be 'before' (default), 'after' or 'off' runs median despiking after or before realignment 
%               'VDM' cellarray of file on drive (to apply field map distorsion correction - see spmup_compute_vdm.m)
%               'motionexp' 'off' (default) or 'on' compute voltera motion expansion
%               'scrubbing' 'on' (default) or 'off' find outliers in motion derivatives and in globals
%               'norm' 'T1norm' (default) or 'EPInorm' choice of the type of template for normalization
%               'norm_res' can be any voxel size, 'EPI' or 'EPI-iso' (default - round to nearest isotropic voxel size)
%               'skernel' is the smoothing kernel as how many times the voxel size
%                         [] as default because 'derivatives' default is 1 (and hrf re-estimation needs re-smoothing) 
%                         using [] means smooth by norm_res, GLM, correct, and re-smooth 3*norm_res
%               'GLM', 'on' (default) or 'off' to compute the simple GLM (see spm_BIDS_1rstlevel.m)
%               'derivatives' to include '1'st (default), '2'nd or '0' derivatives in the model
%                             --> when the 1st derivative is included, the hrf amplitude estimates are
%                                 automatcally 'boosted' and time delay also computed
%               'carpet_plot' is 'on' (default) or 'off' to display GLM residuals voxels in 2D 
%                            (like for resting state - if denoised, and regressed propertly, 
%                             residuals should be clean)
%
% see also see spmup_compute_vdm.m and spm_BIDS_1rstlevel.m 
%
% Cyril Pernet July 2022
% --------------------------
%  Copyright (C) SPMUP Team 

options = struct(...
    'outdir', [BIDS_dir filesep 'derivatives'], ...
    'keep_data', 'off',  ...
    'overwrite_data', 'on', ...
    'QC', 'on', ...
    'anat',[], ...
    'reorient','on', ...
    'task',[], ...
    'acq',[], ...
    'rec',[], ...
    'removeNvol', 0, ...
    'despike', 'before', ...
    'VDM', [], ...
    'motionexp', 'off', ...
    'scrubbing', 'on', ...
    'norm', 'T1norm', ...
    'norm_res', 'EPI-iso', ...
    'skernel', [], ...
    'GLM', 'on', ...
    'derivatives', 1, ...
    'carpet_plot', 'on');
